create index if not exists idx_profiles_org on public.profiles(organisation_id);
create index if not exists idx_clients_org on public.clients(organisation_id);
create index if not exists idx_contacts_client on public.client_contacts(client_id);
create index if not exists idx_sites_org_client on public.sites(organisation_id, client_id);
create index if not exists idx_buildings_site on public.buildings(site_id);
create index if not exists idx_systems_building on public.systems(building_id);
create index if not exists idx_equipment_org_building on public.equipment(organisation_id, building_id);
create index if not exists idx_equipment_type on public.equipment(equipment_type_id);
create index if not exists idx_equipment_next_inspection on public.equipment(next_inspection_at);
create index if not exists idx_plans_org_active on public.maintenance_plans(organisation_id, active);
create index if not exists idx_jobs_org_date on public.maintenance_jobs(organisation_id, scheduled_date);
create index if not exists idx_jobs_assignee_status on public.maintenance_jobs(assigned_technician_id, status);
create index if not exists idx_job_equipment_job on public.job_equipment(job_id);
create index if not exists idx_inspections_job on public.inspections(job_id);
create index if not exists idx_inspections_technician on public.inspections(technician_id);
create index if not exists idx_results_inspection on public.inspection_results(inspection_id);
create index if not exists idx_findings_org_status on public.findings(organisation_id, status);
create index if not exists idx_findings_job on public.findings(job_id);
create index if not exists idx_finding_photos_finding on public.finding_photos(finding_id);
create index if not exists idx_reports_org_status on public.reports(organisation_id, status);
create index if not exists idx_reports_job on public.reports(job_id);
create index if not exists idx_audit_org_created on public.audit_logs(organisation_id, created_at desc);
create index if not exists idx_notifications_recipient on public.notifications(recipient_id, status, created_at desc);
create index if not exists idx_equipment_metadata_gin on public.equipment using gin(metadata);
